/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarkaRouteImport } from './routes/marka'
import { Route as MarkaGirisiRouteImport } from './routes/marka-girisi'
import { Route as MarkaKayitRouteImport } from './routes/marka-kayit'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PartnerBasvuruRouteImport } from './routes/partner-basvuru'
import { Route as PartnerGirisiRouteImport } from './routes/partner-girisi'
import { Route as YonetimRouteImport } from './routes/yonetim'
import { Route as YonetimGirisiRouteImport } from './routes/yonetim-girisi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkaRoute = MarkaRouteImport.update({
  id: '/marka',
  path: '/marka',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkaGirisiRoute = MarkaGirisiRouteImport.update({
  id: '/marka-girisi',
  path: '/marka-girisi',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkaKayitRoute = MarkaKayitRouteImport.update({
  id: '/marka-kayit',
  path: '/marka-kayit',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerBasvuruRoute = PartnerBasvuruRouteImport.update({
  id: '/partner-basvuru',
  path: '/partner-basvuru',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerGirisiRoute = PartnerGirisiRouteImport.update({
  id: '/partner-girisi',
  path: '/partner-girisi',
  getParentRoute: () => rootRouteImport,
} as any)
const YonetimRoute = YonetimRouteImport.update({
  id: '/yonetim',
  path: '/yonetim',
  getParentRoute: () => rootRouteImport,
} as any)
const YonetimGirisiRoute = YonetimGirisiRouteImport.update({
  id: '/yonetim-girisi',
  path: '/yonetim-girisi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marka': typeof MarkaRoute
  '/marka-girisi': typeof MarkaGirisiRoute
  '/marka-kayit': typeof MarkaKayitRoute
  '/partner': typeof PartnerRoute
  '/partner-basvuru': typeof PartnerBasvuruRoute
  '/partner-girisi': typeof PartnerGirisiRoute
  '/yonetim': typeof YonetimRoute
  '/yonetim-girisi': typeof YonetimGirisiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marka': typeof MarkaRoute
  '/marka-girisi': typeof MarkaGirisiRoute
  '/marka-kayit': typeof MarkaKayitRoute
  '/partner': typeof PartnerRoute
  '/partner-basvuru': typeof PartnerBasvuruRoute
  '/partner-girisi': typeof PartnerGirisiRoute
  '/yonetim': typeof YonetimRoute
  '/yonetim-girisi': typeof YonetimGirisiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marka': typeof MarkaRoute
  '/marka-girisi': typeof MarkaGirisiRoute
  '/marka-kayit': typeof MarkaKayitRoute
  '/partner': typeof PartnerRoute
  '/partner-basvuru': typeof PartnerBasvuruRoute
  '/partner-girisi': typeof PartnerGirisiRoute
  '/yonetim': typeof YonetimRoute
  '/yonetim-girisi': typeof YonetimGirisiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/marka'
    | '/marka-girisi'
    | '/marka-kayit'
    | '/partner'
    | '/partner-basvuru'
    | '/partner-girisi'
    | '/yonetim'
    | '/yonetim-girisi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/marka'
    | '/marka-girisi'
    | '/marka-kayit'
    | '/partner'
    | '/partner-basvuru'
    | '/partner-girisi'
    | '/yonetim'
    | '/yonetim-girisi'
  id:
    | '__root__'
    | '/'
    | '/marka'
    | '/marka-girisi'
    | '/marka-kayit'
    | '/partner'
    | '/partner-basvuru'
    | '/partner-girisi'
    | '/yonetim'
    | '/yonetim-girisi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarkaRoute: typeof MarkaRoute
  MarkaGirisiRoute: typeof MarkaGirisiRoute
  MarkaKayitRoute: typeof MarkaKayitRoute
  PartnerRoute: typeof PartnerRoute
  PartnerBasvuruRoute: typeof PartnerBasvuruRoute
  PartnerGirisiRoute: typeof PartnerGirisiRoute
  YonetimRoute: typeof YonetimRoute
  YonetimGirisiRoute: typeof YonetimGirisiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marka': {
      id: '/marka'
      path: '/marka'
      fullPath: '/marka'
      preLoaderRoute: typeof MarkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marka-girisi': {
      id: '/marka-girisi'
      path: '/marka-girisi'
      fullPath: '/marka-girisi'
      preLoaderRoute: typeof MarkaGirisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marka-kayit': {
      id: '/marka-kayit'
      path: '/marka-kayit'
      fullPath: '/marka-kayit'
      preLoaderRoute: typeof MarkaKayitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-basvuru': {
      id: '/partner-basvuru'
      path: '/partner-basvuru'
      fullPath: '/partner-basvuru'
      preLoaderRoute: typeof PartnerBasvuruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-girisi': {
      id: '/partner-girisi'
      path: '/partner-girisi'
      fullPath: '/partner-girisi'
      preLoaderRoute: typeof PartnerGirisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yonetim': {
      id: '/yonetim'
      path: '/yonetim'
      fullPath: '/yonetim'
      preLoaderRoute: typeof YonetimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yonetim-girisi': {
      id: '/yonetim-girisi'
      path: '/yonetim-girisi'
      fullPath: '/yonetim-girisi'
      preLoaderRoute: typeof YonetimGirisiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarkaRoute: MarkaRoute,
  MarkaGirisiRoute: MarkaGirisiRoute,
  MarkaKayitRoute: MarkaKayitRoute,
  PartnerRoute: PartnerRoute,
  PartnerBasvuruRoute: PartnerBasvuruRoute,
  PartnerGirisiRoute: PartnerGirisiRoute,
  YonetimRoute: YonetimRoute,
  YonetimGirisiRoute: YonetimGirisiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
